spring:
  devtools:
    restart:
      enabled: false
  datasource:
    testWhileIdle: true
    validationQuery: select 1
    initialize: false
    url: jdbc:mysql://127.0.0.1:3306/retail2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
  thymeleaf:
    cache: false
  messages:
    encoding: UTF-8
    basename: messages
  http:
    encoding:
      charset: UTF-8
    multipart:
      max-file-size: 10240576
      